name: Generate Api Docs

on: [push]

jobs:
  build:

    # The OS on which the job will run
    runs-on: ubuntu-latest

    steps:

      # A GitHub action to setup Node.js
      - uses: actions/setup-node@master
        with:
          node-version: "12"

      # Run the NPM install command before proceeding
      - run: npm install

      - run: apidoc -c staging -f .js -i ./routes -o doc-staging/